name: my_audio_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # For recording audio from the mic (supports recording and playback)
  flutter_sound: ^9.2.13

  mic_stream:
    path: ./mic_stream_fixed


  web_socket_channel: ^2.1.0
  # For handling runtime permissions (e.g., microphone)
  permission_handler: 11.4.0
  # For making HTTP requests to your Node.js backend
  http: ^0.13.5
  # For getting file system paths (e.g., to save your recorded file)
  path_provider: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
